### ISSUE TITLE
Performance tuning and best practice for OpenMP

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#17]
We need a section on getting the most out of OpenMP : both generic (e.g. top ten tips for OpenMP, pointing to further documentation) and specific for ARCHER2 and AMD EPYC Zen2 (will need at least the TDS for this). Should also cover what functionality is available in the various PrgEnv and what is not.

**Comment by aturner-epcc** [comment]
Content for "Profiling and performance tuning" section: https://github.com/ARCHER2-HPC/archer2-docs/blob/master/user-guide/profile.rst

**Comment by xguo-epcc** [comment]
As raised by StephenB: "I'm not sure the documentation is particularly clear when it comes to hyperthreads. The hardware description just says 128 cores  but the OS and slurm sees 256 cpus per node because of the hyperthreads. I have not seen anything incorrect but it might be confusing." - Shall we add hyperthreading as one of the tips for using OpenMP?

**Comment by aturner-epcc** [comment]
@markb-epcc Did you manage to add anything on this?
