### ISSUE TITLE
How to use mpirun on ARCHER2?

### ISSUE THREAD

**Issue by Zihe33Huang** [ARCHER2-HPC/archer2-docs#518]
is it possible to directly use `mpirun` to run programs on ARCHER2, because when I type it, it occured that "the command not found"

**Comment by aturner-epcc** [comment]
Short answer is: no, you cannot use `mpirun` on ARCHER2. All MPI software should be launched using `srun` instead of `mpirun`. Description of how to launch parallel jobs is in the documentation at:

https://docs.archer2.ac.uk/user-guide/scheduler/#srun-launching-parallel-jobs

I will raise a new query in the ARCHER2 service desk so we can discuss this further with you and provide support.
